/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: "403",
    path: "/403",
    component: "layout.blank$view.403",
    meta: {
      title: "403",
      i18nKey: "route.403",
      constant: true,
      hideInMenu: true,
    },
  },
  {
    name: "404",
    path: "/404",
    component: "layout.blank$view.404",
    meta: {
      title: "404",
      i18nKey: "route.404",
      constant: true,
      hideInMenu: true,
    },
  },
  {
    name: "500",
    path: "/500",
    component: "layout.blank$view.500",
    meta: {
      title: "500",
      i18nKey: "route.500",
      constant: true,
      hideInMenu: true,
    },
  },
  {
    name: "config",
    path: "/config",
    component: "layout.base",
    meta: {
      title: "config",
      i18nKey: "route.config",
      icon: "mdi:cog",
      order: 3,
    },
    children: [
      {
        name: "config_admin",
        path: "/config/admin",
        component: "view.config_admin",
        meta: {
          title: "config_admin",
          i18nKey: "route.config_admin",
          icon: "mdi:shield-account",
          order: 3,
        },
      },
      {
        name: "config_blacklist",
        path: "/config/blacklist",
        meta: {
          title: "config_blacklist",
          i18nKey: "route.config_blacklist",
          icon: "mdi:account-multiple-remove",
          order: 4,
        },
        children: [
          {
            name: "config_blacklist_group",
            path: "/config/blacklist/group",
            component: "view.config_blacklist_group",
            meta: {
              title: "config_blacklist_group",
              i18nKey: "route.config_blacklist_group",
              icon: "mdi:account-multiple-remove",
              order: 1,
            },
          },
          {
            name: "config_blacklist_personal",
            path: "/config/blacklist/personal",
            component: "view.config_blacklist_personal",
            meta: {
              title: "config_blacklist_personal",
              i18nKey: "route.config_blacklist_personal",
              icon: "mdi:account-remove",
              order: 2,
            },
          },
        ],
      },
      {
        name: "config_service",
        path: "/config/service",
        component: "view.config_service",
        meta: {
          title: "config_service",
          i18nKey: "route.config_service",
          icon: "mdi:server",
          order: 2,
        },
      },
      {
        name: "config_subscription",
        path: "/config/subscription",
        component: "view.config_subscription",
        meta: {
          title: "config_subscription",
          i18nKey: "route.config_subscription",
          icon: "mdi:bell-ring-outline",
          order: 6,
        },
      },
      {
        name: "config_whitelist",
        path: "/config/whitelist",
        meta: {
          title: "config_whitelist",
          i18nKey: "route.config_whitelist",
          icon: "mdi:account-multiple-check",
          order: 5,
        },
        children: [
          {
            name: "config_whitelist_group",
            path: "/config/whitelist/group",
            component: "view.config_whitelist_group",
            meta: {
              title: "config_whitelist_group",
              i18nKey: "route.config_whitelist_group",
              icon: "mdi:account-multiple-check",
              order: 1,
            },
          },
          {
            name: "config_whitelist_personal",
            path: "/config/whitelist/personal",
            component: "view.config_whitelist_personal",
            meta: {
              title: "config_whitelist_personal",
              i18nKey: "route.config_whitelist_personal",
              icon: "mdi:account-check",
              order: 2,
            },
          },
        ],
      },
    ],
  },
  {
    name: "document",
    path: "/document",
    component: "layout.base$view.document",
    meta: {
      title: "document",
      i18nKey: "route.document",
      icon: "mdi:file-document-outline",
      order: 998,
    },
  },
  {
    name: "home",
    path: "/home",
    component: "layout.base$view.home",
    meta: {
      title: "home",
      i18nKey: "route.home",
      icon: "mdi:monitor-dashboard",
      order: 1,
    },
  },
  {
    name: "iframe-page",
    path: "/iframe-page/:url",
    component: "layout.blank$view.iframe-page",
    props: true,
    meta: {
      title: "iframe-page",
      i18nKey: "route.iframe-page",
      constant: true,
      hideInMenu: true,
      keepAlive: true,
    },
  },
  {
    name: "local-data",
    path: "/local-data",
    component: "layout.base",
    meta: {
      title: "local-data",
      i18nKey: "route.local-data",
      icon: "mdi:database",
      order: 5,
    },
    children: [
      {
        name: "local-data_warframe",
        path: "/local-data/warframe",
        meta: {
          title: "local-data_warframe",
          i18nKey: "route.local-data_warframe",
          icon: "mdi:gamepad-variant",
          order: 1,
        },
        children: [
          {
            name: "local-data_warframe_alias",
            path: "/local-data/warframe/alias",
            component: "view.local-data_warframe_alias",
            meta: {
              title: "local-data_warframe_alias",
              i18nKey: "route.local-data_warframe_alias",
              icon: "mdi:tag-text-outline",
              order: 1,
            },
          },
          {
            name: "local-data_warframe_lich-sister",
            path: "/local-data/warframe/lich-sister",
            component: "view.local-data_warframe_lich-sister",
            meta: {
              title: "local-data_warframe_lich-sister",
              i18nKey: "route.local-data_warframe_lich-sister",
              icon: "mdi:skull-crossbones",
              order: 5,
            },
          },
          {
            name: "local-data_warframe_market",
            path: "/local-data/warframe/market",
            component: "view.local-data_warframe_market",
            meta: {
              title: "local-data_warframe_market",
              i18nKey: "route.local-data_warframe_market",
              icon: "mdi:store-outline",
              order: 2,
            },
          },
          {
            name: "local-data_warframe_market-riven",
            path: "/local-data/warframe/market-riven",
            component: "view.local-data_warframe_market-riven",
            meta: {
              title: "local-data_warframe_market-riven",
              i18nKey: "route.local-data_warframe_market-riven",
              icon: "mdi:diamond-stone",
              order: 3,
            },
          },
          {
            name: "local-data_warframe_night-wave",
            path: "/local-data/warframe/night-wave",
            component: "view.local-data_warframe_night-wave",
            meta: {
              title: "local-data_warframe_night-wave",
              i18nKey: "route.local-data_warframe_night-wave",
              icon: "mdi:signal",
              order: 6,
            },
          },
          {
            name: "local-data_warframe_nodes",
            path: "/local-data/warframe/nodes",
            component: "view.local-data_warframe_nodes",
            meta: {
              title: "local-data_warframe_nodes",
              i18nKey: "route.local-data_warframe_nodes",
              icon: "mdi:vector-arrange-below",
              order: 7,
            },
          },
          {
            name: "local-data_warframe_phantom",
            path: "/local-data/warframe/phantom",
            component: "view.local-data_warframe_phantom",
            meta: {
              title: "local-data_warframe_phantom",
              i18nKey: "route.local-data_warframe_phantom",
              icon: "mdi:ghost",
              order: 4,
            },
          },
          {
            name: "local-data_warframe_relics",
            path: "/local-data/warframe/relics",
            component: "view.local-data_warframe_relics",
            meta: {
              title: "local-data_warframe_relics",
              i18nKey: "route.local-data_warframe_relics",
              icon: "mdi:treasure-chest",
              order: 8,
            },
          },
          {
            name: "local-data_warframe_reward-pool",
            path: "/local-data/warframe/reward-pool",
            component: "view.local-data_warframe_reward-pool",
            meta: {
              title: "local-data_warframe_reward-pool",
              i18nKey: "route.local-data_warframe_reward-pool",
              icon: "mdi:gift-outline",
              order: 9,
            },
          },
          {
            name: "local-data_warframe_riven-analyse",
            path: "/local-data/warframe/riven-analyse",
            component: "view.local-data_warframe_riven-analyse",
            meta: {
              title: "local-data_warframe_riven-analyse",
              i18nKey: "route.local-data_warframe_riven-analyse",
              icon: "mdi:chart-timeline-variant",
              order: 10,
            },
          },
          {
            name: "local-data_warframe_riven-tion",
            path: "/local-data/warframe/riven-tion",
            component: "view.local-data_warframe_riven-tion",
            meta: {
              title: "local-data_warframe_riven-tion",
              i18nKey: "route.local-data_warframe_riven-tion",
              icon: "mdi:format-list-text",
              order: 11,
            },
          },
          {
            name: "local-data_warframe_riven-tion-alias",
            path: "/local-data/warframe/riven-tion-alias",
            component: "view.local-data_warframe_riven-tion-alias",
            meta: {
              title: "local-data_warframe_riven-tion-alias",
              i18nKey: "route.local-data_warframe_riven-tion-alias",
              icon: "mdi:tag-multiple-outline",
              order: 12,
            },
          },
          {
            name: "local-data_warframe_state-translation",
            path: "/local-data/warframe/state-translation",
            component: "view.local-data_warframe_state-translation",
            meta: {
              title: "local-data_warframe_state-translation",
              i18nKey: "route.local-data_warframe_state-translation",
              icon: "mdi:translate",
              order: 13,
            },
          },
          {
            name: "local-data_warframe_warframes",
            path: "/local-data/warframe/warframes",
            component: "view.local-data_warframe_warframes",
            meta: {
              title: "local-data_warframe_warframes",
              i18nKey: "route.local-data_warframe_warframes",
              icon: "mdi:shield",
              order: 14,
            },
          },
          {
            name: "local-data_warframe_weapons",
            path: "/local-data/warframe/weapons",
            component: "view.local-data_warframe_weapons",
            meta: {
              title: "local-data_warframe_weapons",
              i18nKey: "route.local-data_warframe_weapons",
              icon: "mdi:sword-cross",
              order: 15,
            },
          },
        ],
      },
    ],
  },
  {
    name: "log",
    path: "/log",
    component: "layout.base",
    meta: {
      title: "log",
      i18nKey: "route.log",
      icon: "mdi:clipboard-text-outline",
      order: 2,
    },
    children: [
      {
        name: "log_command",
        path: "/log/command",
        component: "view.log_command",
        meta: {
          title: "log_command",
          i18nKey: "route.log_command",
          icon: "mdi:console",
          order: 1,
        },
      },
      {
        name: "log_real-time",
        path: "/log/real-time",
        component: "view.log_real-time",
        meta: {
          title: "log_real-time",
          i18nKey: "route.log_real-time",
          icon: "mdi:timeline-text",
          order: 2,
        },
      },
    ],
  },
  {
    name: "login",
    path: "/login",
    component: "layout.blank$view.login",
    meta: {
      title: "login",
      i18nKey: "route.login",
      constant: true,
      hideInMenu: true,
    },
  },
  {
    name: "reward",
    path: "/reward",
    component: "layout.base$view.reward",
    meta: {
      title: "reward",
      i18nKey: "route.reward",
      icon: "mdi:currency-twd",
      order: 999,
    },
  },
];
