name: Build and Upload NyxBot-WebUI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build NyxBot-WebUI
        run: pnpm build

      - name: Upload WebUi Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webui-build
          path: ./resources
